package zeroone.developers.payapp

enum class ErrorCodes(val code:Int) {

    CATEGORY_NOT_FOUND(100),
    CATEGORY_ALREADY_EXISTS(101),

    PRODUCT_NOT_FOUND(200),
    PRODUCT_ALREADY_EXISTS(201),
    PRODUCT_NOT_ENOUGH(202),

    TRANSACTION_NOT_FOUND(300),
    TRANSACTION_ALREADY_EXISTS(301),

    TRANSACTION_ITEM_NOT_FOUND(400),
    TRANSACTION_ITEM_ALREADY_EXISTS(401),

    USER_NOT_FOUND(500),
    USER_ALREADY_EXISTS(501),

    USER_PAYMENT_TRANSACTION_NOT_FOUND(600),
    USER_PAYMENT_TRANSACTION_ALREADY_EXISTS(601)




}
